stages:
  - build

build_image:
  stage: build
  cache: {}
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo $DOCKER_HUB_TOKEN | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  script:
    - docker build --tag "$DOCKER_HUB_IMAGE" .
    - docker push "$DOCKER_HUB_IMAGE"
  only:
    - main
  variables:
    DOCKER_HUB_IMAGE: tandyn/rpt23-proxy-server
