stages:
  - build
  - deploy

build_image:
  stage: build
  cache: {}
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo $DOCKER_HUB_TOKEN | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  script:
    - docker build --tag "$DOCKER_HUB_IMAGE" .
    - docker push "$DOCKER_HUB_IMAGE"
  only:
    - main
  variables:
    DOCKER_HUB_IMAGE: tandyn/rpt23-proxy-server

deploy_ec2:
  stage: deploy
  cache: {}
  tags:
    - tandy
  script:
    - ssh ec2-user@$DEPLOY_SERVER "df -hT && docker-compose pull && docker-compose down -v && docker-compose up -d && docker rmi $(docker images -q --filter "dangling=true") && df -hT"
  only:
    - main
